# Generated by Django 5.2.8 on 2025-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("developer", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                (
                    "game_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload .py or .zip file",
                        null=True,
                        upload_to="games/",
                    ),
                ),
                (
                    "game_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to source code or playable version",
                        null=True,
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("pygame", "Pygame"),
                            ("console", "Console Script"),
                            ("web", "Web/PyScript"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
