# Generated by Django 5.2.8 on 2025-11-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="browser_build",
            field=models.FileField(
                blank=True,
                help_text="Upload .zip of HTML/WASM build for browser play",
                null=True,
                upload_to="builds_zip/",
            ),
        ),
    ]
